## Numpy

In [1]:
!python -m pip install numpy

In [2]:
import numpy as np

### Numpy Array

In [3]:
num_list = [1, 2, 3, 4]
int_arr2 = np.array(num_list)
print(type(num_list), type(int_arr2))
print(num_list)
print(int_arr2)

<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]


### 배열의 범위를 지정하여 생성
시작 인덱스부터 시작하여 끝 인덱스 전까지, 간격만큼  더해 넘파이 배열 생성.
- np.arange (시작 인덱스 : 끝 인덱스 : 간격) 

In [ ]:
np.arange(0, 10) # 0 ~ 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2) # 0 ~ 9, step = 2

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(5) # 0 ~ 4

array([0, 1, 2, 3, 4])

넘파이(NumPy) 배열은 무조건 모든 요소가 '동일한 데이터 타입'이어야 하는 규칙 존재.
- 배열 전체를 가장 표현 범위가 넓은 자료형으로 업캐스팅(Upcasting).
- Boolean ➡️ Integer ➡️ Float ➡️ String 힘이 더 센 쪽(우측)으로 통합.

In [ ]:
np.array([1, '2', 3]) # string

array(['1', '2', '3'], dtype='<U21')

In [ ]:
np.array([1, 2., 3]) # float

array([1., 2., 3.])

### 2차원 배열 생성
2차원 배열은 행렬(matrix)이라고 한다. 
- 가로줄은 행(row), 세로줄은 열(column)

In [10]:
arr1 = np.array(
    [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]
)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 3차원 배열 생성
3차원 이상의 배열은 tensor라고 한다.

In [13]:
arr2 = np.array(
    [
        [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]],
        
        [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]    
    ]
)
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기
- .ndim(Number of Dimensions) # 배열의 차원을 정수(Integer)로 반환
- .shape(Shape of Array) # 배열의 각 차원의 크기(길이)를 튜플(Tuple) 형태로 반환

In [16]:
print(arr1.ndim, arr1.shape)

2 (3, 4)


In [15]:
print(arr2.ndim, arr2.shape)

3 (2, 3, 4)


In [ ]:
arr3 = np.arange(1,11)

print(arr3)
print(arr3.ndim, arr3.shape)
# (10,) != (10)
# (10,) != (10,0)
# (10,) != (10,1)

[ 1  2  3  4  5  6  7  8  9 10]
1 (10,)


### 배열의 차원 변경
- .reshape

In [20]:
arr4 = arr3.reshape(2, 5)
print(arr4.ndim, arr4.shape)
print(arr4)

2 (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
arr5 = arr3.reshape(-1, 5)
print(arr5.ndim, arr5.shape)
print(arr5)

2 (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Numpy 연산
- shape이 같다면 덧셈, 뺄셈, 곱셈, 나눗셈의 연산을 수행할 수 있다. 
- 벡터화 연산, 요소별 연산(Element-wise): 동일한 인덱스끼리 연산.

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [23]:
print(a + 1)
print(a - 3)
print(a * 3)
print(a / 2)

[2 3 4]
[-2 -1  0]
[3 6 9]
[0.5 1.  1.5]


### 배열의 범위와 개수를 지정하여 생성
시작 인덱스부터 끝 인덱스까지 n개의 요소를 갖는 넘파이 배열을 생성
- np.linspace(시작 인덱스 :  끝 인덱스 :  개수 n) 

In [24]:
arr6 = np.linspace(1, 10, 10)
print(arr6.dtype)
print(arr6)

float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [25]:
arr7 = np.linspace(0, np.pi, 10)
print(arr7.dtype)
print(arr7)

float64
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


### 특별한 값을 갖는 배열 생성
- np.zeros()
- np.ones()
- np.eye()

In [27]:
arr8 = np.zeros(10)
print(arr8)

arr9 = np.zeros(10, dtype=int)
print(arr9)

arr10 = np.zeros((2, 5))
print(arr10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### NumPy 배열 연산하기
- 벡터화 연산(vectorized operation)을 지원
- 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리

In [29]:
data1 = list(range(0, 10))
print(data1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
data2 = []
for i in data1:
    data2.append(i * 2)
data2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

리스트 컴프리헨션(List Comprehension)

In [31]:
data3 = [i * 2 for i in data1]
data3

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

내장 함수 map()과 내임명(익명) 함수 lambda(람다)를 조합한 데이터 변환 문법

In [32]:
list(map(lambda i: i * 2, data1))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [33]:
i = np.array(data1)
2 * i

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

벡터화 연산(Vectorized Operation)'이자 브로드캐스팅(Broadcasting)

In [34]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

도전하기

In [36]:
print(2 * a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [37]:
c = np.array([[0, 1, 2], [3, 4, 5]]) 
c

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
print(c.ndim, c.shape)

2 (2, 3)


In [41]:
d = np.array(
    [
        [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]],

        [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]
    ]
)
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [43]:
print(d.ndim, d.shape, d.size)

3 (2, 3, 4) 24


### Array Indexing

In [44]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


In [54]:
a = np.array([[0, 1, 2], [3, 4, 5]]) # 0, 1, 5 추출

In [53]:
print(a[0, 0])
print(a[0, 1])
print(a[1, 2])

0
1
5


In [55]:
print(a[[0, 0, 1], [0, 1, 2]])

[0 1 5]


In [56]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(a[0])

[0 1 2 3]


### 배열의 슬라이싱

In [78]:
a = np.array([[0, 1, 2], [3, 4, 5]])

print(a[:, 1])
print(a[0:2, 1])

[1 4]
[1 4]


In [79]:
print(a[0])

[0 1 2]


In [80]:
print(a[:2, :2])

[[0 1]
 [3 4]]


In [82]:
k = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(k[:2, :2])

[[0 1]
 [4 5]]


In [83]:
print(k[1, 1:])

[5 6 7]


### 팬시 인덱싱(fancy indexing)
- 데이터베이스의 질의(Query) 기능을 수행.
- 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 ndarray 배열을 받을 수 있다.
- 불리언(Boolean) 배열 방식과 정수 배열 방식.

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

조건문 연산을 사용하여 짝수인 원소만 골라내기

In [85]:
temp1 = a % 2 == 0
temp1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [86]:
a[temp1]

array([0, 2, 4, 6, 8])

In [87]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [95]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[0, 0:4:3])
print(a[1, 0:4:3])
print(a[2, 0:4:3])

[1 4]
[5 8]
[ 9 12]


In [103]:
a[(a % 4 == 0) | (a % 4 == 1)]

array([ 1,  4,  5,  8,  9, 12])

In [106]:
a[[2, 0 , 1]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### 도전하기

다음의 문제를 해결해주세요.

- 배열에서 3의 배수를 찾아주세요.
- 배열에서 4로 나누면 1이 남는 수를 찾아주세요. 
- 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.

In [108]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [109]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [110]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [111]:
x[(x % 3 == 0)|(x % 4 == 1)]

array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18])